# Generated by Django 3.1.6 on 2021-02-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Publish')),
                ('value', models.FloatField(verbose_name='Value')),
                ('serie', models.CharField(max_length=10, verbose_name='Serie ID')),
            ],
        ),
    ]
