name: Build and Deploy Website

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Image
        run: | 
          docker build . --file Dockerfile --tag docker.pkg.github.com/$GITHUB_REPOSITORY/cumplo:latest
          docker login docker.pkg.github.com --username josehbez --password $GH_TOKEN
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/cumplo:latest
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  
      - name: Deploy Production
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.DEPLOY_PASSWORD }}
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          # check this https://docs.github.com/en/packages/guides/configuring-docker-for-use-with-github-packages
          script: |
            [[ ! -d cumplo ]] && git clone https://github.com/josehbez/cumplo.git
            [[ -d cumplo ]] && cd cumplo; git pull
            docker pull docker.pkg.github.com/josehbez/cumplo/cumplo:latest
            docker-compose stop
            docker rm webcumplo || true
            docker-compose up -d
            docker container  exec -it -u 0  webcumplo python cumplo/manage.py migrate